name: Deployment (Container)
on:
  push:
    branches:
      - main
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    # To put a job and its steps into a container, use the "container" keyword
    # You can specify the name of the image to use
    # "node:16" uses the node image of version 16
    container: 
      image: node:16
      # This is the environment variable needed by the image
      # env: 
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb #
      # you can use the label of the connection cantainer as the address
      MONGODB_CLUSTER_ADDRESS: mongodb #cluster0.zq0lm1o.mongodb.net
      MONGODB_USERNAME: root # nokafor
      MONGODB_PASSWORD: example # 6QpL4X96
      PORT: 8080
    # Use the "services" to add service containers
    # services belongs to one job, each job has it's own services
    services:
      # give an optional name "this name is not default to GitLab"
      mongodb:
        # specify the image key
        image: mongo
        # set the env properties for the mongodb image environment variables
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
